### PR TITLE
fix: #28 compilation issue on rn 0.73

### LINKED ISSUE #28: Android: RN 0.73: Build fails to compile C++ source
RN 0.73 fails to build the Android app when including package react-native-quick-base64. This could be an issue with the React Native library itself. Their bug reporting page says to notify the third-party library developer first.

**Steps to reproduce**
_npx react-native init RN073 --version 0.73.0_
_cd RN073_
_yarn add react-native-quick-base64_
_cd android_
_./gradlew assemble_

**Error**
Execution failed for task ':react-native-quick-base64:buildCMakeDebug[arm64-v8a]'.
`[1/5] Building CXX object CMakeFiles/quickbase64.dir/cpp-adapter.cpp.o`
`  FAILED: CMakeFiles/quickbase64.dir/cpp-adapter.cpp.o`

`In file included from RN073/node_modules/react-native-quick-base64/cpp/react-native-quick-base64.cpp:1:`
`In file included from RN073/node_modules/react-native-quick-base64/android/../cpp/react-native-quick-base64.h:1:`
`In file included from RN073/node_modules/react-native/ReactCommon/jsi/jsi/jsilib.h:10:`
`  RN073/node_modules/react-native/ReactCommon/jsi/jsi/jsi.h:1107:23: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?`
`      typename = std::enable_if_t<`
`                 ~~~~~^~~~~~~~~~~`
`                      enable_if`

`Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/type_traits:538:63: note: 'enable_if' declared here`
`  template <bool, class _Tp = void> struct _LIBCPP_TEMPLATE_VIS enable_if {};`

### PR DESCRIPTION
**Pull request by mlecoq**
to fix #28

### CODE REVIEW

**Comment by craftzdog** [comment]
Hey, thanks! Is it backward-compatible?

**Comment by mlecoq** [comment]
I will check :)

**Comment by mlecoq** [comment]
@craftzdog tested on versions from 0.73 to 0.69

**Comment by craftzdog** [comment]
Cool, thanks for checking!

**Pull request merged**
