### PR TITLE
Update C++ code

### PR DESCRIPTION
**Pull request by boorad**
There are a few bug fixes/improvements in Kevin Heifner's [fork](https://github.com/heifner/base64) of `cpp-base64`.  This project was using `2.rc.7`, and the fork has the following changes:

* based from 2.rc.09
  * with a bug fix allowing for unpadded strings
*  modified to be header-only
* templated for various string / char containers
* performance improvements (decoding via lookup table)
   * speed improvements measured at 4x-6x over `v2.0.8`

This PR:
* updates the project to use this fork.
* updates the example app from RN 0.66.3 to 0.73.6
* adds a test suite (from `base64-js` and node's `crypto`)

### CODE REVIEW

**Comment by boorad** [comment]
Android works, but is no faster than `base64-js` on my Pixel 8 Pro.  Any ideas why?

**Comment by craftzdog** [comment]
`base64ToArrayBuffer` is `undefined` when running on Android. So, it seems to be not initialized properly.
Can you look into [op-sqlite](https://github.com/OP-Engineering/op-sqlite/blob/main/android/cpp-adapter.cpp)'s implementation?

**Comment by boorad** [comment]
Yes, will do.  Also, these changes are not yet solving the issue for my PRs in `react-native-quick-crypto`, so I may search for and add some more tests.  Something is still a bit off...

**Comment by boorad** [comment]
@craftzdog I cannot for the life of me figure out what I broke in this branch.  `Unable to resolve module react-native-quick-base64` so I can't run it on either `ios` or `android` right now.  I pushed my changes based on what I saw in rn-quick-crypto, op-sqlite, and rn-vision-camera.  Any ideas?

**Comment by craftzdog** [comment]
I'll look into it next month or so.

**Comment by boorad** [comment]
Found the issue.  Pressing on to fix the original Android problem.

**Comment by boorad** [comment]
Changes to the Example App:
* add test suite results
* clean up benchmarks
* overall layout

Simulator Screenshot - iPhone 15 Pro - 2024-03-24 at 13 24 28
Screenshot_20240324_134601

**Comment by craftzdog** [comment]
It works in my environment!

Screenshot 2024-03-27 at 23 53 52

**Comment by boorad** [comment]
I'm waiting on any required changes to this branch that might be needed in `react-native-quick-crypto` PR's before asking you to review and merge.  I'm stuck on a bad jwk key import, but hopefully will be past that issue soon.  Then we can cut a v2.1.0 release.

**Comment by boorad** [comment]
@craftzdog any idea what's going on with the GHA builds?

**Comment by craftzdog** [comment]
yeah, strange. I tried clearing the GitHub cache but it still doesn't work

**Comment by boorad** [comment]
hmm, you didn't get my squashed commit (force-push)...  I think I can fix it later after the GHA stuff works.

**Comment by craftzdog** [comment]
made the iOS GHA build successful but still no luck with the Android build.
maybe it'd be helpful to look into rn-mmkv's latest code:

https://github.com/mrousavy/react-native-mmkv/commit/94522bdfb822930118c6b2620f963190ff5924de

**Comment by craftzdog** [comment]
no, this one: https://github.com/mrousavy/react-native-mmkv/pull/656/files

**Comment by boorad** [comment]
@craftzdog this is ready for your review.  If you approve, please merge and cut a `v2.1.0` release.

FYI, I found [`act`](https://github.com/nektos/act) to run GHA locally and not spam PRs with tons of commits 👼 

```sh
 act -j build_android_example --remote-name b
```

**Comment by craftzdog** [comment]
Congrats!! Thanks so much for your effort, @boorad  🥳

**Comment by boorad** [comment]
Happy to do it.

Can you cut a tag/release, and publish to npm? 🙏

**Comment by craftzdog** [comment]
published!
https://github.com/craftzdog/react-native-quick-base64/releases/tag/v2.1.0

**Comment by boorad** [comment]
not all the way yet https://www.npmjs.com/package/react-native-quick-base64?activeTab=versions :)

**Comment by boorad** [comment]
~Also, the release and the tag for `v2.1.0` are incorrect.  They missed my commit.  I'm going to try to fix.~

For some reason in my `react-native-quick-crypto` PR, I am not getting a proper dependency download to `node_modules`.  It gets `package.json` at `"2.1.0"`, but `android/CMakeLists.txt` is the old one.  Very weird.  Maybe the npmjs.org publish will help this.

**Comment by craftzdog** [comment]
oh sorry, I didn't realize that it failed to publish due to:

```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
npm http fetch PUT 415 https://registry.npmjs.org/react-native-quick-base64 2086ms
npm ERR! code E415
npm ERR! 415 Unsupported Media Type - PUT https://registry.npmjs.org/react-native-quick-base64 - Hard link is not allowed

npm ERR! A complete log of this run can be found in: /Users/nora/.npm/_logs/2024-04-02T23_51_58_037Z-debug-0.log
```

I'll look into it soon

**Comment by craftzdog** [comment]
It's up. Can you try again?
https://www.npmjs.com/package/react-native-quick-base64/v/2.1.0

**Comment by boorad** [comment]
💥 works like a charm 💥 

Thanks!

**Pull request merged**
